# Generated by Django 5.2.13 on 2026-09-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان محصول')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر بازی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت اصلی')),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('description', models.TextField(verbose_name='توضیحات کامل (تب توضیحات)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Category', models.CharField(max_length=32)),
            ],
        ),
    ]
