# Generated by Django 5.2.13 on 2026-09-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
